### ISSUE TITLE
sDAI Rate Provider Review

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#13]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xc7177b6e18c1abd725f5b75792e5f7a3ba5dbc2c#code

### Protocol Documentation

https://docs.makerdao.com/build/dai.js/savingsservice

### Protocol Audits

https://github.com/makerdao/sdai/blob/master/audits/ChainSecurity_Oazo_Apps_Limited_Savings_Dai_audit_1.pdf

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by rabmarut** [comment]
@Zen-Maxi Confirming your request with an estimated delivery date of next Tuesday, September 19.
