### ISSUE TITLE
Tranchess qETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#17]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xA6aeD7922366611953546014A3f9e93f058756a2#readContract

### Protocol Documentation

https://docs.tranchess.com/

### Protocol Audits

https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-TranchessV2.1-v1.0.pdf

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by rabmarut** [comment]
@Zen-Maxi Confirming with an estimated delivery of Friday, September 29.
