### ISSUE TITLE
Overnight wUSD+ Rate Providers

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#18]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://arbiscan.io/address/0x2bA447d4B823338435057571bF70907F8224BB47#readContract

### Additional Links

Base: https://basescan.org/address/0xe1b1e024f4Bc01Bdde23e891E081b76a1A914ddd
Optimism: https://optimistic.etherscan.io/address/0xe561451322a5efC51E6f8ffa558C7482c892Bc1A#readContract

### Protocol Documentation

https://docs.overnight.fi/

### Protocol Audits

https://docs.overnight.fi/other/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [x] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
If this can be done before 2PM Thursday would be a huge help to get them up for vote before the next Aura round. Apparently they will bribe in large amounts if they do pass the governance vote. 

Their underlying token USD+ can be bridged between networks, but wUSD+ is not bridgeable, meaning there will not be arb opportunities due to the different outputs of each rate provider.

**Comment by baileyspraggins** [comment]
@Zen-Maxi We'll have it done by Friday, September 29th
