### ISSUE TITLE
wUSDK Rate Provider Review

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#20]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xd8689E8740C23d73136744817347fd6aC464E842#readContract

### Protocol Documentation

https://docs.kuma.bond/kuma-protocol/

### Protocol Audits

https://docs.kuma.bond/kuma-protocol/ressources/security-and-audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by baileyspraggins** [comment]
@Zen-Maxi Thanks for submitting this. It will be completed by Tuesday October 3rd.
