### ISSUE TITLE
Staked agEUR Rate Provider - Gnosis

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#25]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://gnosisscan.io/address/0xff315299c4d3fb984b67e31f028724b6a9aeb077#readContract

### Protocol Documentation

https://agavedev.notion.site/agavedev/Agave-Docs-a0cb462422b941d89a6dc646cdb1bdf8

### Protocol Audits

https://drive.google.com/file/d/1qLQdjKGZSO6GR3M46sJEn6NB4U1xLU2B/view

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Agave site is quite thin for links and documentation. It is a an AAVE v2 fork, but i do not know the implications that has for staked EURe in particular.

**Comment by Zen-Maxi** [comment]
Correction, this is angle protocol. This was brought up by mkflow. Docs: https://docs.angle.money/overview/guides/steur
Audits: https://docs.angle.money/resources/audits

**Comment by rabmarut** [comment]
Closed by #26
