### ISSUE TITLE
mevETH Rate Provider Reviewer

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#34]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xf518f2ebea5df8ca2b5e9c7996a2a25e8010014b#code

### Protocol Documentation

https://manifold-lsd-docs.vercel.app/mevETH/overview

### Protocol Audits

https://kebabsec.xyz/audits/manifold_finance_meveth2_audit/

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Please complete this review for the end of next week if possible. Prior to October 26th if possible

**Comment by rabmarut** [comment]
This one seems simple enough. We'll target the middle of next week.
