### ISSUE TITLE
wFRK Rate Provider Review 

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#36]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://polygonscan.com/address/0x76D8B79Fb9afD4dA89913458C90B6C09676628E2#readContract

### Protocol Documentation

https://docs.kuma.bond/kuma-protocol/kuma-protocol/composable-interest-bearing-tokens/kuma-interest-bearing-tokens/frk

### Protocol Audits

https://docs.kuma.bond/kuma-protocol/ressources/security-and-audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
wFRK is a tokenized french t-bill. The goal is deploy the pool on polygon with PAR and jEUR in a composable stable pool. If possible review before next voting round (Nov 30) would be appreciated.

**Comment by rabmarut** [comment]
Will review early next week, before Wednesday Nov 29.

**Comment by rabmarut** [comment]
@Zen-Maxi This review is finished, but I just noticed your pool description:

> The goal is deploy the pool on polygon with PAR and jEUR in a composable stable pool.

This Rate Provider covers the exchange rate between `wFRK` and `FRK`. If `FRK` is pegged to EUR, then this will work. If it's not, it won't. I can't tell for sure either way, so please just keep that in mind when building pools.
