### ISSUE TITLE
osETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#37]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x8023518b2192FB5384DAdc596765B3dD1cdFe471#readContract

### Protocol Documentation

https://docs.stakewise.io/smart-contracts

### Protocol Audits

https://github.com/stakewise/contracts/tree/master/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by rabmarut** [comment]
Will review early next week, before Wednesday Nov 29.

**Comment by mkflow27** [comment]
@rabmarut assigned this one to me.

**Comment by rabmarut** [comment]
Closed by #41
