### ISSUE TITLE
plsRDNT Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [threerocks-defi/code-review#39]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://arbiscan.io/address/0x6dbf2155b0636cb3fd5359fccefb8a2c02b6cb51#readProxyContract

### Protocol Documentation

https://plutusdao-1.gitbook.io/plutus-docs/products/plsassets

### Protocol Audits

https://sourcehat.com/audits/PlvGLP/

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Please put this towards the top of the priority list. Ideally done this week to be voted upon, with time for comments to be addressed in the case of not passing review. Ping me on TG if a discussion with Plutus' developer(s) is needed.

**Comment by rabmarut** [comment]
@Zen-Maxi Please re-read the issue submission form:

> Someone from our team will confirm or reject your submission, or ask for clarity, within 1 business day. Confirmation of the request will be accompanied by an **estimated time to completion which is typically 1 week** and will not exceed 2 weeks.

I've been seeing a lot of "please do this in 2-3 days" requests lately. I will accommodate this one but I'd also ask everyone submitting issues to be respectful of our process and our time. Thank you.

**Comment by Zen-Maxi** [comment]
Sorry rab, this one has be long awaited and is tied to our large partners Radiant and Arbitrum Foundation, as well as a new one, Plutus. It will (hopefully) become one of our strongest value propositions on the network. The extra efforts on your side are greatly appreciated.

**Comment by rabmarut** [comment]
@Zen-Maxi The contract is upgradeable by this EOA: https://arbiscan.io/address/0x482c7e72FC4F1796Ed0f48799e645C1149E05B94

I can't approve an EOA administrator. I'm assuming this will be fixed, so I'll type up the rest of the report and prepare to inject a new admin. Please let me know when it is changed.

In the future, please try to validate the intake checklist on your end. This is included for a reason:
>  If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Ok has been updated to plutus msig https://arbiscan.io/address/0xa5c1c5a67Ba16430547FEA9D608Ef81119bE1876#code Please confirm that this is sufficientm if other changes are needed please advise.
